FROM node

WORKDIR '/usr/app'

COPY package.json .

RUN npm config set registry https://registry.npmmirror.com \
    && npm install \
    && mkdir node_modules/.cache \
    && chmod -R 777 node_modules/.cache

COPY . .

CMD ["npm", "run", "start"]